openapi: 3.0.0
info:
  title: CRM Sistem
  description: Simple CRM Sistem
  version: 1.0.0
servers:
  - url: http://localhost:8080/crm
    description:
paths:
  /roles:
    get:
      summary: Returns a list of roles.
      description:
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  
