openapi: 3.0.0
info:
  description: Simple CRM Sistem
  version: "1.0.0"
  title: CRM Sistem

servers:
  - url: 'http://localhost:8080/crm'

tags:
  - name: roles
    description: Everything about roles
  - name: tasks
    description: Operations about tasks
  - name: users
    description: Operations about user
  - name: auth
    description: login/logout
paths:
  /roles:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - roles
      summary: Return a list of roles
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleDTO'
        '404':
          description: NOT_FOUND
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - roles
      summary: Add a new roles to the CRM
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleDTO'
        required: true
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleDTO'
        '406':
          description: NOT_ACCEPTABLE
  /roles/{id}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - roles
      summary: Returns a role by ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A role object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleDTO'
        '404':
          description: no found DB role by id.
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - roles
      summary: Update an role by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleDTO'
        required: true
      responses:
        '200':
          description: OK
        '304':
          description: NOT_MODIFIED
        '404':
          description: NOT_FOUND
  /roles/{id}/users:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - roles
      summary: Returns all role users by role by id.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Return a list of users.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: NOT FOUND.
  /tasks:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Return a list of tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: NOT_FOUND

    post:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Add a new task to the CRM
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            format: token
            example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZXRyb3YiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2Mzg0MjU0NDQsImV4cCI6MTYzOTAzMDI0NH0.ZUmRQ0eXSAg_TlaD3g9pvrGK0a8E-t6n3YA0_3EZPLg
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDTO'
        required: true
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        '404':
          description: NOT_FOUND
  /tasks/page:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Return a list of tasks
      parameters:
        - name: pageable
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: OK
          content:
              '*/*':
                schema:
                  $ref: '#/components/schemas/PageTaskDTO'
        '404':
          description: NOT_FOUND

  /tasks/{id}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Task by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        '404':
          description: no found DB role by id, NOT_FOUND
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Update an task by id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDTO'
      responses:
        '200':
          description: OK
        '304':
          description: NOT_MODIFIED
        '404':
          description: NOT_FOUND

    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Delete an task by id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '404':
          description: NOT_FOUND

  /tasks/{id}/users:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Return all users by task with id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        '404':
          description: NOT_FOUND

    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Revoke all users from task by id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '404':
          description: NOT_FOUND

  /tasks/{id}/{statis}:
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - tasks
      summary: Change status for task by id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: statis
          in: path
          required: true
          schema:
            type: string
            enum:
              - NEW
              - PROGRESS
              - DONE
      responses:
        '200':
          description: OK
        '404':
          description: NOT_FOUND
  /users:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: Return a list of users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: NOT_FOUND
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: Add a new user to the CRM

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: CREATE
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: NOT_ACCEPTABLE

  /users/{id}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: Returns a user by ID.
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            format: token
            example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZXRyb3YiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2Mzg0MjU0NDQsImV4cCI6MTYzOTAzMDI0NH0.ZUmRQ0eXSAg_TlaD3g9pvrGK0a8E-t6n3YA0_3EZPLg
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: no found DB role by id.
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: Update an user by id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        '200':
          description: OK
        '304':
          description: NOT_MODIFIED
        '404':
          description: NOT_FOUND
    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: delete an user by id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '404':
          description: NOT_FOUND
  /users/{id}/tasks:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: return all tasks by user with id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: NOT_FOUND, no found user in DB
    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: revoke all user tasks from user by id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '304':
          description: NOT_MODIFIED
  /users/{id}/password:
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: update user's password by id
      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordDTOForChanges'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: NOT_FOUND
  /users/{userId}/tasks/{taskId}:
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: assing task to user
      parameters:

        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64

        - name: taskId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '404':
          description: NOT_FOUND
    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - users
      summary: revoke task from user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64

        - name: taskId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '304':
          description: NOT_MODIFIED
  /login:
    post:
      tags:
        - auth
      summary: assing task to user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  login:
                    type: string
                    example: Petrov
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZXRyb3YiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2Mzg1NTYyMjksImV4cCI6MTYzOTE2MTAyOX0.cJUYsXDim2CvnxEz8o_CerUDptkXAvvLDWuWejkeJ_s
        '406':
          description: FORBIDDEN
  /logout:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        -  auth
      operationId: logout
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        login:
          type: string
        psw:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        roleId:
          type: integer
          format: int32
    PasswordDTOForChanges:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
        repeatNewPassword:
          type: string
    TaskDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        status:
          type: string
          enum:
            - NEW
            - PROGRESS
            - DONE
        deadline:
          type: string
          format: date
        info:
          type: string
    RoleDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        roleName:
          type: string
    UserAuthenticationDTO:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
    Pageable:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
    Sort:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
    PageTaskDTO:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/TaskDTO'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
        last:
          type: boolean
        pageable:
          $ref: '#/components/schemas/Pageable'
        numberOfElements:
          type: integer
          format: int32
        empty:
          type: boolean