INSERT INTO crm.status(status_name)
VALUES ('new'),
       ('performed'),
       ('completed');

INSERT INTO crm.role(role_name)
VALUES ('user'),
       ('admin');

INSERT INTO crm.user(login, psw, role, last_name, first_name)
VALUES ('Petrov', 123, 1, 'Petrov', 'Petr'),
       ('Ivanov', 123, 1, 'Ivanov', 'Ivan'),
       ('Sidorov', 123, 1, 'Sidorov', 'Sidr'),
       ('Frolov', 123, 2, 'Frolov', 'Vova'),
       ('Kozlov', 123, 2, 'Kozlov', 'Igor'),
       ('Kolpokova', 123, 2, 'Kolpokova', 'Sveta'),
       ('Kulak', 123, 2, 'Kulak', 'Tanyay'),
       ('Dropalo', 123, 2, 'Dropalo', 'Andrey'),
       ('Kurgan', 123, 2, 'Kurgan', 'Misha'),
       ('Leurdo', 123, 2, 'Leurdo', 'Elena');

INSERT INTO crm.task(title, status, dedline, info)
VALUES ('Design the solution', 1, '2022-10-23', 'Define the relationship between resources and business systems.'),
       ('Prepare for implementation', 1, '2022-12-23', 'Identify production LPARs.'),
       ('Prepare the test/QA environment', 2, '2021-12-23',
        'Verify connectivity from test and QA servers to test LPAR, Tivoli Enterprise Console(R) server, and console machines.'),
       ('Install the product in the test/QA environment.', 1, '2022-10-23',
        'Create configuration level objects for the test LPAR.'),
       ('Implement distributed data feeds (this can be done in parallel with the Source/390 data feed implementation).',
        3, '2019-10-23', 'Configure the Tivoli Enterprise Console rules to send events.'),
       ('Implement a business system in the test/QA environment.', 3, '2018-10-23', null),
       ('Schedule jobs', 2, '2022-10-23', 'Define the relationship between resources and business systems.'),
       ('Prepare the production environment.', 2, '2022-03-15',
        'Define the relationship between resources and business systems.'),
       ('Install the product in the production environment.', 1, '2022-08-23', null),
       ('Implement distributed data feeds in the production environment.', 2, '2022-08-16',
        'Verify the event flow.'),
       ('Implement Source/390 data feeds in the production environment.', 3, '2012-10-23',
        'Configure filtering, if appropriate.'),
       ('Implement a business system in the production environment.', 2, '2032-10-23',
        'Define the relationship between resources and business systems.'),
       ('Install the history server.', 3, '2019-05-23',
        'Define the relationship between resources and business systems.'),
       ('Install the Health Monitor.', 1, '2024-12-25', 'Verify the event flow.'),
       ('Enable the problem/change interface', 1, '2022-10-14', 'Configure filtering, if appropriate.'),
       ('Create and present administrator and operator training information', 2, '2023-04-19',
        '	Consider training a key group and have them train their peers.'),
       ('Create a solution maintenance plan', 2, '2022-05-21', 'Create databases on the history server.'),
       ( 'Schedule jobs date', 1, '2022-07-29', 'Monitor system performance and adjust hardware as required.'),
       ('Database backup and maintenance', 1, '2025-12-30', 'Database backup and maintenance'),
       ('Tivoli Business Systems Manager SQL server jobs', 3, '2020-11-28',
        'Tivoli Business Systems Manager SQL server jobs');

INSERT INTO crm.user_task(
    user_id, task_id, info)
VALUES
    (1, 1, 'info'),
    (1, 2, null),
    (1, 3, 'info'),
    (2, 4, null),
    (2, 5, null),
    (3, 6, null),
    (4, 7,'info'),
    (4, 8, 'info'),
    (4, 9, null),
    (4, 10, 'info'),
    (5, 11, 'info'),
    (5, 12, null),
    (6, 13, 'info'),
    (6, 14, 'info'),
    (6, 15, 'info'),
    (6, 16, 'info'),
    (7, 17, 'info'),
    (7, 18, null),
    (7, 19, null),
    (7, 20, 'info'),
    (8, 1, 'info'),
    (8, 2, 'info'),
    (8, 3, 'info'),
    (9, 4, null),
    (9, 5, null),
    (9, 6, null),
    (10, 7, null),
    (10,8, 'tasks info'),
    (10, 9, 'tasks info'),
    (1, 10, 'tasks info'),
    (2, 11, 'tasks info'),
    (3, 12, null),
    (4, 13, null),
    (5, 14, 'tasks info'),
    (6, 12, 'tasks info'),
    (7, 16, 'tasks info'),
    (8, 17, 'tasks info'),
    (9, 18, null),
    (10, 19, null),
    (1, 20, 'tasks info');